### ISSUE TITLE
请问一下：为什么我搭建出来显示的是ThinkPHP V6.0.6的欢迎页面？

### ISSUE THREAD

**Issue by xingruyubb** [yiqia/student_system#1]
:)
ThinkPHP V6.0.6
14载初心不改 - 你值得信赖的PHP框架

[ V6.0 版本由 亿速云 独家赞助发布 ]

**Comment by yiqia** [comment]
抱歉，之前写的时候没有设置默认跳转路径，搭建好访问/student路径

**Comment by xingruyubb** [comment]
非常感谢！我自己查了一下资料，修改了一下route.php文件，另外还改了 .env中的数据库连接信息 ，已经搭建成功
